# Generated by Django 4.0 on 2024-04-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_headline_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='url',
            new_name='link',
        ),
    ]
