# Generated by Django 4.0 on 2024-04-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_url_headline_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
