# Generated by Django 4.0 on 2025-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_headline_description_alter_headline_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
