import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Terms of Service | Ultra News",
    description: "Terms and conditions for using the Ultra News platform.",
};

export default function TermsPage() {
    return (
        <div className="max-w-3xl mx-auto pt-8 pb-20 px-4">
            <header className="mb-12 border-b border-[var(--border)] pb-8">
                <span className="text-xs font-bold tracking-widest uppercase text-[var(--accent)] mb-4 block">Ultra News</span>
                <h1 className="text-4xl md:text-5xl font-display font-[900] tracking-tighter leading-none text-[var(--foreground)] mb-6">
                    Terms of Service
                </h1>
                <p className="font-data text-[11px] text-[var(--foreground-muted)] uppercase tracking-widest">
                    Last Updated: July 2026
                </p>
            </header>

            <div className="prose prose-lg dark:prose-invert font-serif text-[var(--foreground-muted)]">
                <h2 className="font-display">1. Information Aggregation</h2>
                <p>
                    Ultra News (The Wire Room) is an automated news aggregator and intelligence terminal. We do not employ journalists, nor do we write the articles featured on the platform. All headlines, excerpts, and images belong to their respective original publishers.
                </p>

                <h2 className="font-display">2. AI-Generated Summaries</h2>
                <p>
                    The "AI Summary" blocks displayed on highly corroborated stories are automatically generated by a Large Language Model (LLM) analyzing the semantic content of the underlying articles. <strong>These summaries are not editorial content.</strong> While we strive for absolute accuracy, LLMs can hallucinate. Users must verify the original framing by reading the underlying sources.
                </p>

                <h2 className="font-display">3. "The Trust Graph" & Algorithmic Clustering</h2>
                <p>
                    Our platform automatically calculates "Coverage Velocity" and "Corroboration Rates" based on mathematical models and Semantic Vector Clustering (`pgvector`). These metrics are quantitative measurements of how news propagates across the internet. They do not constitute an endorsement or a definitive statement of truth.
                </p>

                <h2 className="font-display">4. Fair Use & Outbound Linking</h2>
                <p>
                    We operate under the principles of Fair Use. We extract only what is necessary (the title and a brief excerpt) to establish the factual context of a breaking story. Our platform is designed to act as a <em>funnel</em> to the original publishers. We enforce outbound tracking links to ensure the original journalists receive the traffic they deserve.
                </p>

                <h2 className="font-display">5. API Usage</h2>
                <p>
                    Any automated interaction with the Ultra News backend APIs must be authorized. Unauthorized scraping, bulk downloading, or reverse engineering of the vector database is prohibited.
                </p>

                <hr className="border-[var(--border)] my-12" />

                <div className="bg-[var(--surface-elevated)] p-6 rounded-[var(--radius-card)] border border-[var(--border)]">
                    <h3 className="font-data text-[10px] font-bold uppercase tracking-widest text-[var(--wire-red)] mb-2 mt-0">Disclaimer</h3>
                    <p className="text-sm m-0">
                        The platform is provided "as is" without warranties of any kind. By using the terminal, you acknowledge that you are navigating an automated intelligence stream.
                    </p>
                </div>
            </div>
        </div>
    );
}
