import type { Metadata } from 'next';
import Link from 'next/link';

/**
 * Terms.
 *
 * Deliberately short and specific. The clauses that matter here are the ones
 * about what a corroboration count is *not*, because that is the claim a reader
 * might otherwise over-rely on.
 */

export const metadata: Metadata = {
  title: 'Terms',
  description: 'The terms of use for Ultra News, and the limits of what it tells you.',
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="border-t border-[var(--border)] py-9">
      <h2 className="text-display-md font-display mb-4 text-[var(--foreground)]">{title}</h2>
      <div className="text-body-md measure space-y-4 text-[var(--foreground-muted)]">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl">
      <header className="border-b-2 border-[var(--foreground)] pb-7">
        <h1 className="text-display-2xl font-display text-[var(--foreground)]">Terms</h1>
        <p className="text-body-lg measure mt-3 text-[var(--foreground-muted)]">
          Ultra News is an open-source news aggregator, provided free and without
          warranty. Using it means accepting the terms below.
        </p>
      </header>

      <Section title="What this service is">
        <p>
          Ultra News groups reporting from independent newsrooms and shows how
          many of them covered the same event. It displays short excerpts and
          links to the original article. It does not republish, host, or claim
          ownership of anyone&rsquo;s journalism.
        </p>
        <p>
          All articles remain the property of the newsrooms that produced them.
          If you publish here and want your feed removed, open an issue on the
          repository and it will be taken out of the registry.
        </p>
      </Section>

      <Section title="What a corroboration count is not">
        <p>
          The number of outlets on a story measures how many independent
          publishers reported it. It is{' '}
          <strong className="text-[var(--foreground)]">not</strong> a truth score,
          a fact check, or an editorial endorsement. Multiple outlets can and do
          repeat the same mistaken report — that is exactly what a corroboration
          count looks like when it is wrong.
        </p>
        <p>
          Don&rsquo;t rely on Ultra News as the sole basis for any decision that
          matters. Follow the links, read the reporting, and judge for yourself.
          The{' '}
          <Link href="/about" className="text-[var(--accent)] underline underline-offset-2">
            method and its limits
          </Link>{' '}
          are documented in full.
        </p>
      </Section>

      <Section title="AI-generated summaries">
        <p>
          Story briefs and Ask the Wire Room answers are generated by a language
          model from the retrieved reporting. They are not written or reviewed by
          a person, and they can be wrong, incomplete or misleading even when the
          underlying sources are sound. Every brief is labelled as
          machine-written; check it against the sources listed beneath it.
        </p>
      </Section>

      <Section title="Acceptable use">
        <p>
          Don&rsquo;t attempt to overwhelm the service, circumvent its rate
          limits, or scrape it in bulk — the{' '}
          <Link href="/subscribe" className="text-[var(--accent)] underline underline-offset-2">
            RSS feeds
          </Link>{' '}
          exist so you don&rsquo;t have to. Don&rsquo;t use it to build anything
          that misrepresents what a source actually reported.
        </p>
      </Section>

      <Section title="No warranty">
        <p>
          The service is provided &ldquo;as is&rdquo;, without warranty of any
          kind. Feeds go down, clustering makes mistakes, and summaries can be
          wrong. Nobody running this accepts liability for decisions taken on the
          basis of it.
        </p>
      </Section>

      <Section title="The code">
        <p>
          Ultra News is MIT licensed — you are free to run, modify and deploy it.
          These terms cover this deployment; anyone hosting their own sets their
          own.
        </p>
      </Section>
    </div>
  );
}
