import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Terms of Service | Ultra News",
  description: "Terms and conditions governing use of the Ultra News intelligence platform.",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto pt-8 pb-20 px-4">
      <header className="mb-12 border-b-2 border-[var(--foreground)] pb-8">
        <span className="text-xs font-bold tracking-widest uppercase text-[var(--accent)] mb-4 block">Ultra News</span>
        <h1 className="text-4xl md:text-5xl font-display font-[900] tracking-tighter leading-none text-[var(--foreground)] mb-6">
          Terms of Service
        </h1>
        <p className="font-data text-[11px] text-[var(--foreground-muted)] uppercase tracking-widest">
          Last Updated: July 2026
        </p>
      </header>

      {/* Quick nav */}
      <nav className="mb-12 p-4 bg-[var(--surface-elevated)] border border-[var(--border)] rounded-[var(--radius-card)]">
        <span className="font-data text-[10px] font-bold uppercase tracking-widest text-[var(--accent)] block mb-3">Sections</span>
        <div className="flex flex-wrap gap-2">
          {[
            'Information Aggregation',
            'AI-Generated Summaries',
            'Trust Graph & Clustering',
            'Fair Use & Outbound Linking',
            'API Usage',
            'Content Licensing',
            'Prohibited Uses',
            'Disclaimer of Warranties',
            'Limitation of Liability',
            'Modifications to Terms',
            'Governing Law',
            'Contact',
          ].map((section, i) => (
            <a
              key={section}
              href={`#section-${i + 1}`}
              className="font-data text-[11px] text-[var(--foreground-muted)] hover:text-[var(--foreground)] transition-colors px-2 py-1 bg-[var(--background)] border border-[var(--border)] rounded-sm"
            >
              §{i + 1}
            </a>
          ))}
        </div>
      </nav>

      <div className="space-y-12">

        {/* §1 Information Aggregation */}
        <section id="section-1">
          <h2 className="font-display text-2xl font-bold text-[var(--foreground)] mb-4 flex items-center gap-2">
            <span className="font-data text-[12px] text-[var(--accent)]">§1</span>
            Information Aggregation
          </h2>
          <div className="font-serif text-[var(--foreground-muted)] space-y-4 leading-relaxed">
            <p>
              Ultra News (&ldquo;The Wire Room&rdquo;) is an automated news aggregator and intelligence terminal. We do not employ journalists, nor do we write the articles featured on the platform. All headlines, excerpts, and images belong to their respective original publishers.
            </p>
            <p>
              The platform ingests publicly available RSS feeds from {35}+ news sources, extracts structured metadata (title, excerpt, publication date, image URL), and organizes this information into clustered story views for end-user consumption.
            </p>
          </div>
        </section>

        {/* §2 AI-Generated Summaries */}
        <section id="section-2">
          <h2 className="font-display text-2xl font-bold text-[var(--foreground)] mb-4 flex items-center gap-2">
            <span className="font-data text-[12px] text-[var(--accent)]">§2</span>
            AI-Generated Summaries
          </h2>
          <div className="font-serif text-[var(--foreground-muted)] space-y-4 leading-relaxed">
            <p>
              The &ldquo;AI Summary&rdquo; blocks displayed on story pages are automatically generated by analyzing the semantic content of underlying articles. <strong>These summaries are not editorial content and should not be treated as factual reporting.</strong>
            </p>
            <p>
              AI-generated text is clearly labeled in the interface with the disclaimer &ldquo;AI Summary — Not editorial content.&rdquo; Large Language Models (LLMs) can produce inaccurate, incomplete, or misleading summaries. Users must verify claims by reading the original source articles linked within each story.
            </p>
            <p>
              Ultra News makes no warranty regarding the accuracy, completeness, or reliability of AI-generated summaries.
            </p>
          </div>
        </section>

        {/* §3 Trust Graph & Clustering */}
        <section id="section-3">
          <h2 className="font-display text-2xl font-bold text-[var(--foreground)] mb-4 flex items-center gap-2">
            <span className="font-data text-[12px] text-[var(--accent)]">§3</span>
            Trust Graph &amp; Algorithmic Clustering
          </h2>
          <div className="font-serif text-[var(--foreground-muted)] space-y-4 leading-relaxed">
            <p>
              Our platform automatically calculates &ldquo;Coverage Velocity,&rdquo; &ldquo;Corroboration Rates,&rdquo; and &ldquo;Independent Domain Counts&rdquo; based on mathematical models and Semantic Vector Clustering (pgvector with 384-dimensional embeddings).
            </p>
            <p>
              These metrics are quantitative measurements of how news propagates across the internet. They do not constitute an endorsement, a definitive statement of truth, or a judgment on the veracity of any particular story. The tier system (Wire → Developing → Reporting) reflects the <em>breadth of independent coverage</em>, not factual verification.
            </p>
            <p>
              A &ldquo;Corroborated&rdquo; label means 3 or more independent outlets have published coverage of the same event. It does not mean the underlying claims have been fact-checked.
            </p>
          </div>
        </section>

        {/* §4 Fair Use & Outbound Linking */}
        <section id="section-4">
          <h2 className="font-display text-2xl font-bold text-[var(--foreground)] mb-4 flex items-center gap-2">
            <span className="font-data text-[12px] text-[var(--accent)]">§4</span>
            Fair Use &amp; Outbound Linking
          </h2>
          <div className="font-serif text-[var(--foreground-muted)] space-y-4 leading-relaxed">
            <p>
              We operate under the principles of Fair Use. We extract only what is necessary — the title, a brief excerpt (~40 words), and a thumbnail image — to establish the factual context of a breaking story.
            </p>
            <p>
              Our platform is designed to act as a <em>funnel</em> to the original publishers. Every article card, timeline entry, and headline framing view includes a prominent &ldquo;Read original source&rdquo; outbound link directing traffic to the original publisher.
            </p>
          </div>
        </section>

        {/* §5 API Usage */}
        <section id="section-5">
          <h2 className="font-display text-2xl font-bold text-[var(--foreground)] mb-4 flex items-center gap-2">
            <span className="font-data text-[12px] text-[var(--accent)]">§5</span>
            API Usage
          </h2>
          <div className="font-serif text-[var(--foreground-muted)] space-y-4 leading-relaxed">
            <p>
              The Ultra News API (<code className="font-mono text-[var(--foreground)] text-sm">/api/v1/</code>) is provided for integration with authorized clients. Public endpoints (stories, articles, sources) are rate-limited and intended for reasonable personal use.
            </p>
            <p>
              Administrative endpoints require authentication via GitHub Actions OIDC tokens or API keys. Unauthorized use of administrative endpoints is prohibited.
            </p>
          </div>
        </section>

        {/* §6 Content Licensing */}
        <section id="section-6">
          <h2 className="font-display text-2xl font-bold text-[var(--foreground)] mb-4 flex items-center gap-2">
            <span className="font-data text-[12px] text-[var(--accent)]">§6</span>
            Content Licensing
          </h2>
          <div className="font-serif text-[var(--foreground-muted)] space-y-4 leading-relaxed">
            <p>
              All original article content (full text, images, multimedia) remains the intellectual property of the respective publishers. Ultra News displays only excerpts in accordance with Fair Use principles.
            </p>
            <p>
              The Ultra News platform code, UI design, and clustering algorithms are the property of Ultra News. The platform is open-source under the terms specified in the project repository.
            </p>
          </div>
        </section>

        {/* §7 Prohibited Uses */}
        <section id="section-7">
          <h2 className="font-display text-2xl font-bold text-[var(--foreground)] mb-4 flex items-center gap-2">
            <span className="font-data text-[12px] text-[var(--accent)]">§7</span>
            Prohibited Uses
          </h2>
          <div className="font-serif text-[var(--foreground-muted)] space-y-4 leading-relaxed">
            <p>You may not:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Scrape, crawl, or systematically download content from the platform beyond normal browsing</li>
              <li>Reverse engineer the vector database, embedding pipeline, or clustering algorithms</li>
              <li>Bulk download articles, embeddings, or story cluster data</li>
              <li>Use the platform to train machine learning models without explicit permission</li>
              <li>Redistribute aggregated content as if it were original reporting</li>
              <li>Attempt to bypass rate limits, authentication, or access controls</li>
              <li>Use the platform for any unlawful purpose</li>
            </ul>
          </div>
        </section>

        {/* §8 Disclaimer of Warranties */}
        <section id="section-8">
          <h2 className="font-display text-2xl font-bold text-[var(--foreground)] mb-4 flex items-center gap-2">
            <span className="font-data text-[12px] text-[var(--accent)]">§8</span>
            Disclaimer of Warranties
          </h2>
          <div className="bg-[var(--surface-elevated)] p-6 rounded-[var(--radius-card)] border border-[var(--border)]">
            <p className="font-serif text-[var(--foreground-muted)] leading-relaxed">
              THE PLATFORM IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE.
            </p>
          </div>
        </section>

        {/* §9 Limitation of Liability */}
        <section id="section-9">
          <h2 className="font-display text-2xl font-bold text-[var(--foreground)] mb-4 flex items-center gap-2">
            <span className="font-data text-[12px] text-[var(--accent)]">§9</span>
            Limitation of Liability
          </h2>
          <div className="font-serif text-[var(--foreground-muted)] space-y-4 leading-relaxed">
            <p>
              IN NO EVENT SHALL ULTRA NEWS, ITS CREATOR, OR CONTRIBUTORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR ACCESS TO OR USE OF (OR INABILITY TO ACCESS OR USE) THE SERVICE.
            </p>
            <p>
              Our aggregate liability for all claims related to the service shall not exceed the amount you have paid to Ultra News in the twelve (12) months preceding the claim, or $0 (zero dollars) if no fees have been paid.
            </p>
          </div>
        </section>

        {/* §10 Modifications to Terms */}
        <section id="section-10">
          <h2 className="font-display text-2xl font-bold text-[var(--foreground)] mb-4 flex items-center gap-2">
            <span className="font-data text-[12px] text-[var(--accent)]">§10</span>
            Modifications to Terms
          </h2>
          <div className="font-serif text-[var(--foreground-muted)] space-y-4 leading-relaxed">
            <p>
              We reserve the right to modify these Terms at any time. Material changes will be communicated via a notice on the platform homepage or through a commit to the open-source repository. Continued use of the platform after changes constitutes acceptance of the updated Terms.
            </p>
            <p>
              The &ldquo;Last Updated&rdquo; date at the top of this page reflects the most recent revision.
            </p>
          </div>
        </section>

        {/* §11 Governing Law */}
        <section id="section-11">
          <h2 className="font-display text-2xl font-bold text-[var(--foreground)] mb-4 flex items-center gap-2">
            <span className="font-data text-[12px] text-[var(--accent)]">§11</span>
            Governing Law
          </h2>
          <div className="font-serif text-[var(--foreground-muted)] space-y-4 leading-relaxed">
            <p>
              These Terms shall be governed by and construed in accordance with applicable law, without regard to conflict of law principles. Any disputes arising from these Terms shall be resolved through good-faith negotiation before any formal proceedings.
            </p>
          </div>
        </section>

        {/* §12 Contact */}
        <section id="section-12">
          <div className="bg-[var(--surface-elevated)] p-6 rounded-[var(--radius-card)] border border-[var(--border)]">
            <h3 className="font-data text-[10px] font-bold uppercase tracking-widest text-[var(--accent)] mb-2 mt-0 flex items-center gap-2">
              <span className="font-data text-[12px]">§12</span>
              Contact
            </h3>
            <p className="text-sm font-serif text-[var(--foreground-muted)] m-0">
              For questions regarding these Terms, please{' '}
              <a href="https://github.com/emmanuelrichard01/ULTRA-NEWS/issues" className="text-[var(--foreground)] font-semibold hover:underline">
                open an issue on GitHub
              </a>{' '}
              or contact the maintainer through the repository.
            </p>
          </div>
        </section>

      </div>
    </div>
  );
}
