# Generated by Django 5.2.15 on 2026-07-05 06:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date']},
        ),
        migrations.AddField(
            model_name='article',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of normalized content for deduplication.', max_length=64),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='~40 word excerpt for display. Full text stored in RawDocument.'),
        ),
        migrations.AddField(
            model_name='article',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='fetch_interval_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('raw_content', models.TextField(help_text='Full extracted text. Internal use only — AI processing, embeddings.')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_document', to='core.article')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_documents', to='core.source')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary or lead paragraph. Clearly labeled in UI.')),
                ('first_seen_at', models.DateTimeField()),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('source_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('developing', 'Developing'), ('corroborated', 'Corroborated')], default='developing', max_length=20)),
                ('categories', models.ManyToManyField(blank=True, related_name='stories', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-first_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='story',
            field=models.ForeignKey(blank=True, help_text='The story cluster this article belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.story'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_date'], name='article_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source', '-published_date'], name='article_source_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='article_search_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='rawdocument',
            index=models.Index(fields=['-fetched_at'], name='rawdoc_fetched_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-first_seen_at'], name='story_first_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['status', '-first_seen_at'], name='story_status_idx'),
        ),
    ]
