# Generated by Django 5.2.15 on 2026-07-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_article_options_article_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_primary_source',
            field=models.BooleanField(default=False, help_text='True if this was the earliest published report in the cluster.'),
        ),
        migrations.AddField(
            model_name='story',
            name='velocity_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Trending score based on accumulation rate of sources.'),
        ),
    ]
