# Generated by Django 5.2.15 on 2026-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_article_is_primary_source_story_velocity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('news', 'News Outlet'), ('primary', 'Primary Source (Gov/Corporate)')], default='news', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='independent_count',
            field=models.PositiveIntegerField(default=1, help_text='Unique independent domains in cluster'),
        ),
        migrations.AlterField(
            model_name='story',
            name='source_count',
            field=models.PositiveIntegerField(default=1, help_text='Total articles in cluster'),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('wire', 'The Wire'), ('developing', 'Developing'), ('corroborated', 'Reporting')], default='wire', max_length=20),
        ),
    ]
