# Generated by Django 5.2.15 on 2026-07-05 17:20

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='articles_broken_first',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this source was the primary (earliest) article in a Corroborated story.'),
        ),
        migrations.AddField(
            model_name='source',
            name='corroboration_rate',
            field=models.FloatField(default=0.0, help_text="Percentage of this source's articles that reach the Corroborated tier."),
        ),
        migrations.AddField(
            model_name='story',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
