# Generated by Django 5.2.16 on 2026-07-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_article_embedding_source_articles_broken_first_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(condition=models.Q(('story__isnull', True)), fields=['story'], name='article_no_story_idx'),
        ),
    ]
