# Generated by Django 5.2.16 on 2026-07-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_url_length_increase'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-velocity_score', '-first_seen_at', '-id'], name='story_cursor_idx'),
        ),
    ]
