# Generated by Django 5.2.16 on 2026-07-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_story_story_cursor_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='trust_tier',
            field=models.CharField(choices=[('auto_publish', 'Auto Publish'), ('review_queue', 'Review Queue')], default='review_queue', help_text='Sources in review_queue require manual approval before articles appear in public feeds.', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='ai_summary',
            field=models.JSONField(blank=True, help_text='Structured multi-source intelligence brief generated by Gemini.', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='synthesis_source_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of articles in cluster when last synthesized.'),
        ),
        migrations.AddField(
            model_name='story',
            name='synthesis_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('pending', 'Synthesis Pending'), ('completed', 'Synthesis Completed'), ('failed', 'Synthesis Failed')], db_index=True, default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='synthesized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
