# Generated by Django 5.2.17 on 2026-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_vector_ann_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='deactivated_reason',
            field=models.CharField(blank=True, help_text='Set when the circuit breaker disables a persistently failing source.', max_length=300),
        ),
        migrations.AddField(
            model_name='source',
            name='etag',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='source',
            name='last_error',
            field=models.CharField(blank=True, help_text='Why the most recent fetch failed. Empty when healthy.', max_length=300),
        ),
        migrations.AddField(
            model_name='source',
            name='last_modified',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='source',
            name='last_success_at',
            field=models.DateTimeField(blank=True, help_text='Last time this source returned a parseable feed.', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, help_text='Last time a fetch was ATTEMPTED (success or failure).', null=True),
        ),
    ]
