# Generated by Django 5.2.17 on 2026-08-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_source_health_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='synthesis_independent_count',
            field=models.PositiveIntegerField(default=0, help_text='Independent publishers in cluster when last synthesized. This — not the article count — is what decides whether re-synthesis is worth paying for: a second article from an outlet already represented adds almost nothing to a multi-source brief, whereas a new outlet does.'),
        ),
    ]
