# Generated by Django 5.2.17 on 2026-08-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_synthesis_independent_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at', 'story'], name='article_recent_idx'),
        ),
    ]
