# Generated by Django 5.2.17 on 2026-08-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_article_recent_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='momentum_computed_at',
            field=models.DateTimeField(blank=True, help_text='When momentum_outlets was last recomputed. Momentum DECAYS as the window slides, so a stale value silently overstates it.', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='momentum_outlets',
            field=models.PositiveIntegerField(default=0, help_text='Independent publishers that published on this story inside the momentum window. Materialised, because computing it per request meant a filtered COUNT(DISTINCT) joined across every article of every story on the page.'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(condition=models.Q(('momentum_outlets__gt', 0)), fields=['-momentum_outlets', '-last_updated_at', '-id'], name='story_momentum_idx'),
        ),
    ]
