# Generated by Django 5.2.17 on 2026-09-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_article_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='feed_tags',
            field=models.JSONField(blank=True, default=list, help_text="The publisher's own RSS <category> terms, kept as a topic hint."),
        ),
        migrations.AddField(
            model_name='article',
            name='topic_scores',
            field=models.JSONField(blank=True, help_text="Topic evidence {slug: score} from core.topics.topic_evidence; the story's consensus is computed from these.", null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='primary_category',
            field=models.ForeignKey(blank=True, help_text="The story's main topic by publisher consensus (core.topics.story_topics). Listed first wherever topics are shown.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_stories', to='core.category'),
        ),
    ]
